(() => {
  'use strict';
  const $ = (id) => document.getElementById(id); let csrfToken = '', page = 1, pages = 1;
  async function csrf() { if (csrfToken) return csrfToken; csrfToken = (await (await fetch('/api/csrf')).json()).csrfToken; return csrfToken; }
  async function api(url, options = {}) { const method = options.method || 'GET', headers = { ...(options.headers || {}) }; if (!['GET','HEAD'].includes(method)) headers['x-csrf-token'] = await csrf(); const response = await fetch(url, { ...options, headers }); const body = response.status === 204 ? null : await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.message || body?.error || '请求失败'); return body; }
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const when = (value) => value ? new Date(value.replace(' ', 'T') + (value.includes('Z') ? '' : 'Z')).toLocaleString() : '永久';
  function enter(admin) { $('loginCard').hidden = true; $('dashboard').hidden = false; window.CONTENT_MANAGER = admin; $('adminIdentity').textContent = `${admin.platform ? '平台管理员' : '内容中心'}：${admin.username}`; if (admin.platform) return loadLogs(); document.body.classList.add('content-manager'); const open = () => { const select=$('qSystem'),tab=document.querySelector('[data-tab="questions"]'); if(!select||!tab)return setTimeout(open,50); const allowed=new Set(admin.systems.map(x=>x.system_code)); [...select.options].forEach(x=>{if(x.value&&!allowed.has(x.value))x.remove()}); select.value=admin.systems[0].system_code; tab.click(); }; open(); }
  async function loadLogs(next = page) { page = next; const q = new URLSearchParams({ page, pageSize: 25, search: $('search').value, status: $('status').value }); const data = await api(`/api/admin/login-logs?${q}`); pages = Math.max(1, data.pagination.pages); $('logRows').innerHTML = data.items.map((x) => `<tr><td>${when(x.created_at)}</td><td>${esc(x.account_type)}<br><b>${esc(x.username)}</b></td><td>${esc(x.ip_address)}</td><td><span class="badge ${esc(x.login_status)}">${esc(x.login_status)}</span></td><td class="ua">${esc(x.user_agent)}</td><td><button class="danger" data-ban-ip="${esc(x.ip_address)}">封禁</button></td></tr>`).join('') || '<tr><td colspan="6">没有记录</td></tr>'; $('pager').innerHTML = `<button id="prev" ${page <= 1 ? 'disabled' : ''}>上一页</button><span>${page} / ${pages}（${data.pagination.total} 条）</span><button id="next" ${page >= pages ? 'disabled' : ''}>下一页</button>`; $('prev').onclick = () => loadLogs(page - 1); $('next').onclick = () => loadLogs(page + 1); }
  async function loadBans() { const data = await api('/api/admin/banned-ips'); $('banRows').innerHTML = data.items.map((x) => `<tr><td>${esc(x.ip_address)}</td><td>${esc(x.reason || '—')}</td><td>${when(x.expires_at)}</td><td>${esc(x.created_by)}</td><td><button class="danger" data-unban="${x.id}">解封</button></td></tr>`).join('') || '<tr><td colspan="5">没有封禁项</td></tr>'; }
  async function loadAudit() { const data = await api('/api/admin/audit-logs'); $('auditRows').innerHTML = data.items.map((x) => `<tr><td>${when(x.created_at)}</td><td>${esc(x.admin)}</td><td>${esc(x.action)}</td><td>${esc(x.target || '—')}</td><td>${esc(x.ip_address)}</td></tr>`).join('') || '<tr><td colspan="5">没有审计记录</td></tr>'; }
  async function loadMemberships() { const systemCode = $('membershipSystem').value; const data = await api(`/api/admin/memberships${systemCode ? `?systemCode=${systemCode}` : ''}`); $('membershipRows').innerHTML = data.items.map((x) => `<tr data-user="${x.user_id}" data-system="${esc(x.system_code)}"><td><b>${esc(x.username)}</b><br>${esc(x.email || '旧账号未设置邮箱')}</td><td>${x.system_code === 'hobby' ? '音乐爱好者' : '高考音乐生'}</td><td><select data-field="role"><option value="learner" ${x.role === 'learner' ? 'selected' : ''}>学习者</option><option value="teacher" ${x.role === 'teacher' ? 'selected' : ''}>教师</option><option value="admin" ${x.role === 'admin' ? 'selected' : ''}>管理员</option></select></td><td><select data-field="status"><option value="active" ${x.status === 'active' ? 'selected' : ''}>正常</option><option value="suspended" ${x.status === 'suspended' ? 'selected' : ''}>暂停</option></select></td><td><button data-save-membership>保存</button></td></tr>`).join('') || '<tr><td colspan="5">没有账号</td></tr>'; }
  $('loginForm').onsubmit = async (event) => { event.preventDefault(); $('loginMessage').textContent = ''; try { const body = await api('/api/admin/login', { method: 'POST', headers: {'content-type':'application/json'}, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); csrfToken = body.csrfToken; enter({ ...body.admin,platform:true,systems:[{system_code:'hobby',role:'admin'},{system_code:'gaokao',role:'admin'}] }); } catch (error) { $('loginMessage').textContent = error.message; } };
  $('searchBtn').onclick = () => loadLogs(1); $('search').onkeydown = (e) => { if (e.key === 'Enter') loadLogs(1); }; $('status').onchange = () => loadLogs(1);
  document.querySelector('nav').onclick = (event) => { const tab = event.target.dataset.tab; if (!tab) return; document.querySelectorAll('.tab').forEach((x) => x.hidden = x.id !== tab); document.querySelectorAll('[data-tab]').forEach((x) => x.classList.toggle('active', x.dataset.tab === tab)); if (tab === 'memberships') loadMemberships(); if (tab === 'bans') loadBans(); if (tab === 'audit') loadAudit(); };
  $('membershipSystem').onchange = loadMemberships;
  $('membershipRows').onclick = async (event) => { if (!event.target.hasAttribute('data-save-membership')) return; const row = event.target.closest('tr'); await api(`/api/admin/memberships/${row.dataset.user}/${row.dataset.system}`, { method:'PATCH', headers:{'content-type':'application/json'}, body:JSON.stringify({ role:row.querySelector('[data-field="role"]').value, status:row.querySelector('[data-field="status"]').value }) }); event.target.textContent = '已保存'; setTimeout(() => event.target.textContent = '保存', 900); };
  $('logRows').onclick = (event) => { const ip = event.target.dataset.banIp; if (!ip) return; document.querySelector('[data-tab="bans"]').click(); $('banForm').elements.ipAddress.value = ip; };
  $('banForm').onsubmit = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const expiresAt = data.duration ? new Date(Date.now() + Number(data.duration) * 3_600_000).toISOString() : null; await api('/api/admin/banned-ips', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ ipAddress:data.ipAddress, reason:data.reason, expiresAt }) }); event.currentTarget.reset(); loadBans(); };
  $('banRows').onclick = async (event) => { const id = event.target.dataset.unban; if (!id) return; await api(`/api/admin/banned-ips/${id}`, { method:'DELETE' }); loadBans(); };
  $('logout').onclick = async () => { await api('/api/admin/logout', { method:'POST' }); location.reload(); };
  api('/api/admin/session').then((body) => body.manager && enter(body.manager)).catch(() => {});
  import('/admin-homework.js');
  import('/admin-questions.js');
})();
